# Numpy

## 创建ndarray多维数组

|属性|说明|
|:--:|:--:|
|ndim|返回int。表示数组的维数|
|shape|返回tuple。表示数组的尺寸(n, m), n行m列的矩阵|
|size|返回int。表示数组的元素总数。shape的乘积|
|dtype|返回data-type。描述数组中元素的类型|
|itemsize|返回int。表示数组每个元素的大小|

创建： `numpy.array(object, dtype = None, copy = True, order = 'K', subok = False, ndmin = 0)`

|参数名称|说明|
|:--:|:--:|
|object|接受array。表示想要创建的数组|
|dtype|接受data-type。表示数组所需的数据类型。如果未给定，则为最小|
|ndmin|接受int。指定数组具有的最小维数|



- 用`reshape`改变数组形状

In [17]:
import numpy as np
a = np.array([[1, 2, 3],[1, 2, 4]])
a.size
a.shape
a.ndim
a.dtype
a.itemsize
a.shape = 3, 2
print(a)

[[1 2]
 [3 1]
 [2 4]]


### arange函数创建数组

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace函数创建数组

- 等差数列

In [21]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### logspace函数创建数组

- 等比数列

In [25]:
np.logspace(0, 10, 10, endpoint=False, base=2)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

### zeros函数创建全零数组

In [26]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### eye函数创建单位矩阵

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### diag函数创建对角线数组

In [28]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### 使用ones函数创建全1数组

In [29]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 数据类型转换

In [30]:
np.float32(17)

17.0

## 生成随机数

### 无约数条件下生成随机数

In [32]:
np.random.random(10) # 0-1的随机数

array([0.04432497, 0.79281113, 0.95991813, 0.83350089, 0.35351659,
       0.85744125, 0.91077652, 0.9883447 , 0.96750121, 0.16530764])

### 生成服从均匀分布的随机数

In [34]:
np.random.rand(2, 5)

array([[0.78005443, 0.70226363, 0.50596482, 0.37395834, 0.71283069],
       [0.7040831 , 0.31902719, 0.94682194, 0.30413788, 0.09177402]])

### 生成服从正态分布的随机数

In [36]:
np.random.randn(2,5)

array([[-2.36958768,  1.01005526,  0.45521447, -0.24496107,  0.73156815],
       [-0.87959129, -0.93689153, -0.46016613, -0.18664932,  0.92466233]])

### 生成给定上下范围的随机数

In [45]:
np.random.randint(low = 2, high = 5, size = [2,3])

array([[4, 3, 3],
       [4, 3, 2]])

|函数|说明|
|:--:|:--:|
|seed|确定生成随机数的种子|
|permutation|返回一个序列的随机排列|
|shuffle|对一个序列进行随机排序|
|binomial|产生二项分布的随机数|
|beta|产生beta分布的随机数|
|chisquare|产生卡方分布的随机数|
|gamma|产生gamma分布的随机数|
|uniform|产生在`[0,1)`中均匀分布的随机数| 

## 通过索引访问数组

- 一维数组同list索引
- 多维数组用逗号隔开，或者用布尔数组

In [47]:
print(a[0,0:2])

[1 2]


## 改变数组形态

- 使用reshape函数改变数组形状
- 使用ravel函数展平数组
- 使用flatten函数展平数组

In [54]:
a.reshape(2,3)
a.ravel()
a.flatten()

array([1, 2, 3, 1, 2, 4])

### 组合数组

- 使用hstack函数横向组合数组
- 使用vstack函数纵向组合数组
- 使用concatenate函数实现数组组合，axis=1横向，axis=0纵向

In [62]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[0,0,0],[9,9,9]])
np.hstack((a,b))
np.vstack((a,b))
np.concatenate((a,b),axis= 1)

array([[1, 2, 3, 0, 0, 0],
       [4, 5, 6, 9, 9, 9]])

### 切割数组

- 使用hsplit横向切割
- 使用vsplit纵向切割
- 使用split切割，axis=1横向，axis=0纵向

In [66]:
np.hsplit(a,1)
np.vsplit(a,2)
np.split(a,2,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

---

## 矩阵和通用函数